export const TEMPLATES = {
  metropolitan: {
    id: "metropolitan",
    name: "The Metropolitan Monolith",
    description: "Urban luxury — authoritative, architectural, sophisticated",
    target: "High-rise developments, downtown lofts",
    colors: {
      bg: "#0F1110",
      text: "#F4F1EA",
      accent: "#C5A059",
      cardBg: "#1A1C1B",
      muted: "#8A8A82",
      border: "#2A2C2B",
    },
    fonts: { heading: "'Playfair Display', serif", body: "'Inter', sans-serif" },
    radius: "2px",
    heroStyle: "split-overlay",
  },
  verdant: {
    id: "verdant",
    name: "The Lumina Verdant",
    description: "Suburban wellness — airy, organic, serene",
    target: "Garden-style apartments, eco-conscious communities",
    colors: {
      bg: "#F7F9F6",
      text: "#2D3436",
      accent: "#5D7052",
      cardBg: "#FFFFFF",
      muted: "#7B8B7A",
      border: "#D4DDD1",
    },
    fonts: { heading: "'DM Sans', sans-serif", body: "'Outfit', sans-serif" },
    radius: "32px",
    heroStyle: "float-grid",
  },
  kinetic: {
    id: "kinetic",
    name: "The Kinetic Atelier",
    description: "Young professional / tech — dynamic, bold, tech-forward",
    target: "Co-living spaces, studio apartments",
    colors: {
      bg: "#FFFFFF",
      text: "#000000",
      accent: "#581CFF",
      cardBg: "#F5F3FF",
      muted: "#6B7280",
      border: "#E5E7EB",
    },
    fonts: { heading: "'Space Grotesk', sans-serif", body: "'Inter', sans-serif" },
    radius: "8px",
    heroStyle: "deck-slide",
  },
  heritage: {
    id: "heritage",
    name: "The Heritage",
    description: "Classic serif, earth tones — timeless elegance",
    target: "Historic conversions, brownstones",
    colors: {
      bg: "#FAF8F5",
      text: "#3C2F2F",
      accent: "#8B6F47",
      cardBg: "#FFFFFF",
      muted: "#9C8E82",
      border: "#E0D5C7",
    },
    fonts: { heading: "'Libre Baskerville', serif", body: "'Source Sans 3', sans-serif" },
    radius: "4px",
    heroStyle: "bordered-classic",
  },
  zenith: {
    id: "zenith",
    name: "The Zenith",
    description: "Ultra-minimalist, centered typography — peak sophistication",
    target: "Luxury high-rise, penthouses",
    colors: {
      bg: "#FAFAFA",
      text: "#1A1A1A",
      accent: "#0A0A0A",
      cardBg: "#FFFFFF",
      muted: "#999999",
      border: "#EEEEEE",
    },
    fonts: { heading: "'Cormorant Garamond', serif", body: "'Inter', sans-serif" },
    radius: "0px",
    heroStyle: "centered-minimal",
  },
  panorama: {
    id: "panorama",
    name: "The Panorama",
    description: "Landscape-oriented, wide gutters — expansive views",
    target: "Resort-style, waterfront properties",
    colors: {
      bg: "#F0F4F8",
      text: "#1B2A4A",
      accent: "#2563EB",
      cardBg: "#FFFFFF",
      muted: "#64748B",
      border: "#CBD5E1",
    },
    fonts: { heading: "'Montserrat', sans-serif", body: "'Open Sans', sans-serif" },
    radius: "12px",
    heroStyle: "wide-landscape",
  },
  brut: {
    id: "brut",
    name: "The Brut",
    description: "Raw concrete textures, heavy typography — no-frills",
    target: "Industrial lofts, warehouse conversions",
    colors: {
      bg: "#E8E4E0",
      text: "#1C1917",
      accent: "#DC2626",
      cardBg: "#D6D3CF",
      muted: "#78716C",
      border: "#A8A29E",
    },
    fonts: { heading: "'Oswald', sans-serif", body: "'IBM Plex Sans', sans-serif" },
    radius: "0px",
    heroStyle: "brutalist-stack",
  },
  velvet: {
    id: "velvet",
    name: "The Velvet",
    description: "Dark mode, serif fonts — high-end hospitality",
    target: "Boutique apartments, luxury rentals",
    colors: {
      bg: "#1A1020",
      text: "#F5F0EB",
      accent: "#D4A574",
      cardBg: "#251A30",
      muted: "#9B8EA8",
      border: "#3D2E4A",
    },
    fonts: { heading: "'Cormorant Garamond', serif", body: "'Nunito Sans', sans-serif" },
    radius: "8px",
    heroStyle: "dark-luxe",
  },
  canvas: {
    id: "canvas",
    name: "The Canvas",
    description: "White-space heavy, art-gallery style — designer appeal",
    target: "Designer lofts, creative districts",
    colors: {
      bg: "#FFFFFF",
      text: "#111111",
      accent: "#111111",
      cardBg: "#F9F9F9",
      muted: "#888888",
      border: "#E0E0E0",
    },
    fonts: { heading: "'EB Garamond', serif", body: "'Work Sans', sans-serif" },
    radius: "0px",
    heroStyle: "gallery-minimal",
  },
  pulse: {
    id: "pulse",
    name: "The Pulse",
    description: "Vivid gradients, interactive hover effects — energetic",
    target: "Student housing, vibrant communities",
    colors: {
      bg: "#FFFBF5",
      text: "#1E1B4B",
      accent: "#F97316",
      cardBg: "#FFFFFF",
      muted: "#6366F1",
      border: "#E0E7FF",
    },
    fonts: { heading: "'Sora', sans-serif", body: "'Inter', sans-serif" },
    radius: "16px",
    heroStyle: "gradient-wave",
  },
  nordic: {
    id: "nordic",
    name: "The Nordic",
    description: "Minimalist, functional, wood-textures — high legibility",
    target: "Suburban family, Scandinavian-inspired communities",
    colors: {
      bg: "#F5F0EB",
      text: "#2C2520",
      accent: "#4A7C59",
      cardBg: "#FFFFFF",
      muted: "#8E8279",
      border: "#D9CFC5",
    },
    fonts: { heading: "'Fraunces', serif", body: "'Karla', sans-serif" },
    radius: "6px",
    heroStyle: "clean-nordic",
  },
  prism: {
    id: "prism",
    name: "The Prism",
    description: "Geometric shapes, overlapping images — playful but professional",
    target: "Mixed-use developments, young families",
    colors: {
      bg: "#FAFBFF",
      text: "#1F2937",
      accent: "#7C3AED",
      cardBg: "#FFFFFF",
      muted: "#9CA3AF",
      border: "#DDD6FE",
    },
    fonts: { heading: "'Plus Jakarta Sans', sans-serif", body: "'Inter', sans-serif" },
    radius: "20px",
    heroStyle: "geometric-overlap",
  },
};

export const getTemplate = (id) => TEMPLATES[id] || TEMPLATES.metropolitan;

export const DEFAULT_PROPERTY = {
  name: "The Residences",
  tagline: "Luxury Living Redefined",
  description: "Experience unparalleled luxury in the heart of the city.",
  hero_headline: "Welcome Home",
  hero_subheadline: "Where Modern Living Meets Timeless Elegance",
  hero_text: "Discover thoughtfully designed residences crafted for those who demand the extraordinary.",
  address: "123 Main Street",
  city: "New York",
  state: "NY",
  zip: "10001",
  phone: "(555) 123-4567",
  email: "leasing@theresidences.com",
  office_hours: "Mon-Fri 9AM-6PM, Sat 10AM-5PM, Sun 12PM-5PM",
  resident_portal_url: "#",
  management_company: "Premier Property Management",
  amenities: [
    { name: "Rooftop Pool", description: "Resort-style pool with panoramic views", icon: "Waves", category: "community" },
    { name: "Fitness Center", description: "State-of-the-art gym with personal training", icon: "Dumbbell", category: "fitness" },
    { name: "Pet Spa", description: "On-site grooming and play area", icon: "PawPrint", category: "pet" },
    { name: "Co-Working Lounge", description: "Professional workspace with high-speed WiFi", icon: "Laptop", category: "tech" },
    { name: "Covered Parking", description: "Secure garage with EV charging stations", icon: "Car", category: "parking" },
    { name: "Garden Courtyard", description: "Landscaped outdoor gathering space", icon: "TreePine", category: "outdoor" },
  ],
  faqs: [
    { question: "What lease terms are available?", answer: "We offer 6, 12, and 18-month lease terms to fit your lifestyle." },
    { question: "Is there a pet policy?", answer: "We are a pet-friendly community welcoming cats and dogs with a small monthly pet rent." },
    { question: "What utilities are included?", answer: "Water, sewer, and trash are included. Residents are responsible for electricity and internet." },
    { question: "Is renter's insurance required?", answer: "Yes, all residents must carry a minimum renter's insurance policy." },
    { question: "How do I submit a maintenance request?", answer: "You can submit requests 24/7 through the Resident Portal or by calling our office." },
  ],
  features: [
    { title: "Smart Home Technology", description: "Every unit features keyless entry and smart thermostats." },
    { title: "Quartz Countertops", description: "Premium finishes throughout every kitchen and bathroom." },
    { title: "In-Unit Washer/Dryer", description: "Full-size appliances in every home for your convenience." },
  ],
  pet_policy: "Cats and dogs welcome. $300 pet deposit, $35/month pet rent. Breed restrictions may apply.",
  lease_terms: "6, 12, and 18-month lease terms available.",
};

export const DEFAULT_UNITS = [
  { unit_type: "Studio", bedrooms: 0, bathrooms: 1, sqft: 550, price: 1450, status: "available", available_date: "2026-05-01" },
  { unit_type: "1 Bedroom", bedrooms: 1, bathrooms: 1, sqft: 750, price: 1850, status: "available", available_date: "2026-05-01" },
  { unit_type: "2 Bedroom", bedrooms: 2, bathrooms: 2, sqft: 1050, price: 2450, status: "available", available_date: "2026-06-01" },
  { unit_type: "3 Bedroom", bedrooms: 3, bathrooms: 2, sqft: 1350, price: 3200, status: "coming_soon", available_date: "2026-07-01" },
];